kind: Service
apiVersion: v1
metadata:
  name: spark-websocket
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: spark-websocket
    role: webapp